sudo: required
services:
  - docker

before_install:
  - docker build -t tahmid-saj/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true USERNAME/react-test npm test

after_success:
  - docker build -t tahmid-saj/multi-client ./client
  - docker build -t tahmid-saj/multi-nginx ./nginx
  - docker build -t tahmid-saj/multi-server ./server
  - docker build -t tahmid-saj/multi-worker ./worker

  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take images and push to docker hub
  - docker push tahmidsaj/multi-client
  - docker push tahmidsaj/multi-nginx
  - docker push tahmidsaj/multi-server
  - docker push tahmidsaj/multi-worker
